FROM nginx:alpine

COPY index.html /usr/share/nginx/html/
COPY logo.png /usr/share/nginx/html/

COPY nginx.conf /etc/nginx/nginx.conf

COPY tls.crt /etc/nginx/certs/tls.crt
COPY tls.key /etc/nginx/certs/tls.key

EXPOSE 443
