apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc
spec:
  type: LoadBalancer
  ports:
    - port: 443
      targetPort: {{ .Values.nginxConf.port }}
      protocol: TCP
      name: https
  selector:
    app: {{ .Release.Name }}-app
