apiVersion: v1
kind: Pod
metadata:
  name: psql-debug
spec:
  containers:
  - name: psql
    image: postgres:15
    command: ["/bin/sh"]
    args: ["-c", "sleep 3600"]
    env:
    - name: PGPASSWORD
      value: "WouldIdeallyFetchFromVault123!"
  restartPolicy: Never

